services:
  - type: web
    name: "77325_peralta"
    runtime: node
    plan: free
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: "secretito"
      - key: LOGE_LEVEL
        value: "info"
      - key: USERS_COUNT
        value: 7
    autoDeploy: true
    branch: main

